### ISSUE TITLE
ModuleScaner - вылет на неинициализированной dll

### ISSUE THREAD

**Issue by Sergeanur** [NtKernelMC/Arthemida-2#35]
Место вылета:
https://github.com/NtKernelMC/Arthemida-2/blob/92f4f72565ed1e62918b58239db07a48543ddd3a/ArtemisComponents/Arthemida-2/ArtModules/ModuleScanner.h#L96
EnumProcessModules, вызванный в параллельном потоке, подхватывает dllки, которые ещё находятся в процессе инициализации. GetModuleFileNameA вызывается на недоступной памяти, от чего процесс вылетает (частый вылет при загрузке client.dll).

**Comment by NtKernelMC** [comment]
Закрыл проблему. Функции те достаточно потокобезопасный судя по мсдну, они референсы на модули насчитывают, добавил и в утиль кучу чеков на нуллптр и тд.
