### ISSUE TITLE
» Этап первый -> Service Scanner

### ISSUE THREAD

**Issue by NtKernelMC** [NtKernelMC/Arthemida-2#50]
- Разработать сканер black-listed сервисов (KMDF/UMDF).
- Проверять корневой сертификат доверия по составленному чёрному списку слитых EV-сертов с паблика которые популярны среди читеров для запуска драйверов не отключая в системе опцию проверки цифровых подписей.
- Смотреть путь с конфигурации сервиса и просканировать его файл на диске на заранее составленные сигнатуры популярных читерских драйверов слитых в паблик, так же учитывать сервисы без путя, есть и службы у которых дллки грузит через netsvc, svchost и много других системных хост-файлов способных через запись в реестре с некоторыми флагами загружать через себя службу, однако не забываем проверять есть ли действительно такая запись у того или иного системного ехешника к длл файлу сервиса на который указывает конфиг, чтобы нельзя было обмануть через фейковый путь ибо системные хост-приложения не загружают модули без корневого сертификата доверия и записи в KnownDlls реестре + там вроде свой внутренний блэк лист есть кое какой, но сильно на него я бы не рассчитывал, мальварщики так инжектят дллки в процессы системы, регают себе службы, дрова и это один из самых популярных способов поднять себе привилегии с помощью прокси дллок, следует смотреть не только саму запись в реестре хост-процесса системы но и наличие загруженного модуля у него в памяти как элементарное подтверждение что он прошел проверку через TrustInstaller а не просто лежит на диске с блэк-листед или во все инвалид сертификатом.
- Обнаружение включенного режима отладки ядра как и отключенную опцию проверки цифровых подписей в системе.
(Назначено holmes0)

**Comment by holmes000** [comment]
Сделано: 
- Service parser 
- Native path handler
- Buffered file pattern scanner
- Failure handling

В прогрессе:

- Optimization: prevent rescanning by keeping fast hash table of files
- Enhancement: grant services scanning priority by known names
- Feature: analyze digital signatures of files
- Feature: get information about system code integrity settings (testsigning, debug mode, etc.)
